version: '3'


services:
  apache:
    build: php/
    ports:
      - 8888:80
    volumes:
      - ./php:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password