version: '3'


services:
  php:
    container_name: php
    build: php/
    expose: 
      - "80"
    volumes:
      - ./php/api/:/var/www/html/
      - ./php/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - HOST=db
      - USERNAME=user
      - PASSWORD=password
      - NAME=appDB
    links:
      - nginx
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/html:/usr/share/nginx/html
    ports:
        - "8000:8000"
    links:
      - mysql

  mysql:
    image: mysql
    container_name: db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password