version: '3'


services:
  # apache:
  #   build: php/
  #   ports:
  #     - 8888:80
  #   volumes:
  #     - ./php:/var/www/html
  #   links:
  #     - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/html:/usr/share/nginx/html
    ports:
        - "8000:8000"
    links:
      - mysql

  mysql:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password